Repository recurly/recurly-client-ruby, pull requests merged in 2019-12, with the labels that each got.

#539 Skip request property type validation for nil values
  .bumpversion.cfg
  lib/recurly/schema/schema_validator.rb
  lib/recurly/version.rb
  spec/recurly/request_spec.rb
Labels: V3, bug

#541 Issue 540 error may have transaction
  .bumpversion.cfg
  lib/recurly/schema/json_parser.rb
  lib/recurly/version.rb
Labels: V3, bug

#544 Release 3.2.0
  .bumpversion.cfg
  GETTING_STARTED.md
  lib/recurly/version.rb
Labels: V3

#535 Reference reactivate href in xml
  lib/recurly/item.rb
Labels: V2

#545 Convert Array params to CSV strings
  .bumpversion.cfg
  lib/recurly/pager.rb
  lib/recurly/version.rb
Labels: V3, bug

#546 Release 2.18.6
  .bumpversion.cfg
  CHANGELOG.md
  README.md
  lib/recurly/version.rb
Labels: V2

#547 Update CHANGELOG.md
  CHANGELOG.md
Labels: V2
