Repository recurly/recurly-client-ruby, pull requests merged in 2020-08, with the labels that each got.

#620 Establish association between Tier and SubscriptionAddOn
  lib/recurly/add_on.rb
  lib/recurly/resource.rb
  lib/recurly/subscription_add_on.rb
  lib/recurly/tier.rb
Labels: V2

#624 Remove site_id and subdomain from client initializer
  lib/recurly/client.rb
  spec/recurly/client_spec.rb
  spec/recurly/pager_spec.rb
  spec/recurly/schema/json_parser_spec.rb
Labels: enhancement

#626 Release 2.18.13
  .bumpversion.cfg
  CHANGELOG.md
  README.md
  lib/recurly/version.rb
Labels: V2

#628 Release 2.18.14
  .bumpversion.cfg
  CHANGELOG.md
  README.md
  lib/recurly/api.rb
  lib/recurly/billing_info.rb
  lib/recurly/version.rb
Labels: V2

#632 Mon Aug 31 19:44:58 UTC 2020 Upgrade API version v2019-10-10
  lib/recurly/requests/coupon_create.rb
  lib/recurly/requests/subscription_change_create.rb
  lib/recurly/resources/subscription_change.rb
  lib/recurly/resources/subscription_change_preview.rb
  openapi/api.yaml
Labels: enhancement

#631 Code of Conduct
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
Labels: documentation
