Repository recurly/recurly-client-ruby, pull requests merged in 2020-04, with the labels that each got.

#576 Add missing association to support Tiered Pricing
  lib/recurly/add_on.rb
  lib/recurly/tier.rb
Labels: V2

#560 Adding #first and #count methods to Pager
  lib/recurly/client.rb
  lib/recurly/http.rb
  lib/recurly/pager.rb
  spec/recurly/client_spec.rb
  spec/recurly/pager_spec.rb
Labels: enhancement

#583 Release 2.18.9
  .bumpversion.cfg
  CHANGELOG.md
  README.md
  lib/recurly/version.rb
Labels: V2

#579 Set an Idempotency-Key header, retry GET requests after 5xx errors
  lib/recurly/client.rb
  spec/recurly/client_spec.rb
Labels: enhancement

#585 Tue Apr 14 20:21:21 UTC 2020 Upgrade API version v2019-10-10
  lib/recurly/requests/add_on_create.rb
  lib/recurly/requests/add_on_update.rb
  lib/recurly/requests/subscription_add_on_create.rb
  lib/recurly/requests/subscription_add_on_tier.rb
  lib/recurly/requests/subscription_add_on_update.rb
  lib/recurly/requests/tier.rb
  lib/recurly/resources/add_on.rb
  lib/recurly/resources/subscription_add_on.rb
  lib/recurly/resources/subscription_add_on_tier.rb
  lib/recurly/resources/tier.rb
  openapi/api.yaml
Labels: enhancement

#581 Fixing the omission of query params
  lib/recurly/client.rb
  lib/recurly/pager.rb
  spec/recurly/client_spec.rb
  spec/recurly/pager_spec.rb
Labels: bug
