Repository recurly/recurly-client-ruby, pull requests merged in 2020-06, with the labels that each got.

#590 Support the programmer passing their own logger
  GETTING_STARTED.md
  lib/recurly/client.rb
  spec/recurly/client_spec.rb
Labels: enhancement

#597 Allow :headers to be included in operations
  lib/recurly/client.rb
  spec/recurly/client_spec.rb
Labels: bug

#595 BACS support
  lib/recurly/billing_info.rb
  spec/fixtures/billing_info/show-bacs-200.xml
  spec/recurly/billing_info_spec.rb
Labels: V2

#603 Merge v2.27 features into v2 branch for release
  lib/recurly/api.rb
  lib/recurly/billing_info.rb
  lib/recurly/plan.rb
  lib/recurly/subscription/add_ons.rb
  lib/recurly/subscription_add_on.rb
  spec/fixtures/billing_info/show-bacs-200.xml
  spec/recurly/billing_info_spec.rb
  spec/recurly/subscription_spec.rb
Labels: V2

#604 Release 2.18.10
  .bumpversion.cfg
  CHANGELOG.md
  README.md
  lib/recurly/version.rb
Labels: V2
