Repository recurly/recurly-client-ruby, pull requests merged in 2020-07, with the labels that each got.

#605 Wed Jul 1 02:06:24 UTC 2020 Upgrade API version v2019-10-10
  lib/recurly/client/operations.rb
  lib/recurly/requests/subscription_add_on_create.rb
  lib/recurly/resources/subscription_add_on.rb
  lib/recurly/resources/subscription_change_preview.rb
  openapi/api.yaml
Labels: enhancement

#608 Mon Jul 6 14:48:05 UTC 2020 Upgrade API version v2019-10-10
  lib/recurly/requests/subscription_add_on_create.rb
  lib/recurly/requests/subscription_add_on_update.rb
  openapi/api.yaml
Labels: enhancement

#614 Release 2.18.11
  .bumpversion.cfg
  CHANGELOG.md
  README.md
  lib/recurly/version.rb
Labels: V2

#615 Fix sub-add-on init bug
  lib/recurly/subscription_add_on.rb
Labels: V2, bug

#617 Release 2.18.12
  .bumpversion.cfg
  CHANGELOG.md
  README.md
  lib/recurly/api.rb
  lib/recurly/billing_info.rb
  lib/recurly/version.rb
  spec/fixtures/billing_info/show-bacs-200.xml
  spec/fixtures/billing_info/show-becs-200.xml
  spec/recurly/billing_info_spec.rb
Labels: V2

#610 Adding hierarchical errors
  lib/recurly/errors/api_errors.rb
  spec/recurly/errors_spec.rb
Labels: enhancement

#618 Remove surcharge as Avalara recommends
  lib/recurly/tax_detail.rb
  spec/fixtures/adjustments/show-200.xml
  spec/fixtures/invoices/show-200-taxed.xml
  spec/recurly/adjustment_spec.rb
  spec/recurly/invoice_spec.rb
Labels: V2

#621 Latest Changes for 2019-10-10 (usage, measured units, etc)
  lib/recurly/client/operations.rb
  lib/recurly/requests/add_on_create.rb
  lib/recurly/requests/add_on_update.rb
  lib/recurly/requests/measured_unit_create.rb
  lib/recurly/requests/measured_unit_update.rb
  lib/recurly/requests/subscription_add_on_create.rb
  lib/recurly/requests/subscription_add_on_update.rb
  lib/recurly/requests/subscription_purchase.rb
  lib/recurly/requests/usage_create.rb
  lib/recurly/resources/add_on.rb
  lib/recurly/resources/add_on_mini.rb
  lib/recurly/resources/measured_unit.rb
  lib/recurly/resources/subscription_add_on.rb
  lib/recurly/resources/subscription_change.rb
  lib/recurly/resources/subscription_change_preview.rb
  lib/recurly/resources/usage.rb
  openapi/api.yaml
Labels: enhancement
