Repository recurly/recurly-client-ruby, pull requests merged in 2021-09, with the labels that each got.

#723 Generated Latest Changes for v2019-10-10 (Dunning Campaigns feature)
  lib/recurly/client/operations.rb
  lib/recurly/requests/account_create.rb
  lib/recurly/requests/account_purchase.rb
  lib/recurly/requests/account_update.rb
  lib/recurly/requests/dunning_campaigns_bulk_update.rb
  lib/recurly/requests/plan_create.rb
  lib/recurly/requests/plan_update.rb
  lib/recurly/resources/account.rb
  lib/recurly/resources/account_mini.rb
  lib/recurly/resources/dunning_campaign.rb
  lib/recurly/resources/dunning_campaigns_bulk_update_response.rb
  lib/recurly/resources/dunning_cycle.rb
  lib/recurly/resources/dunning_interval.rb
  lib/recurly/resources/invoice.rb
  lib/recurly/resources/plan.rb
  openapi/api.yaml
Labels: V3

#724 Generated Latest Changes for v2021-02-25 (Dunning Campaigns feature)
  lib/recurly/client/operations.rb
  lib/recurly/requests/account_create.rb
  lib/recurly/requests/account_purchase.rb
  lib/recurly/requests/account_update.rb
  lib/recurly/requests/dunning_campaigns_bulk_update.rb
  lib/recurly/requests/plan_create.rb
  lib/recurly/requests/plan_update.rb
  lib/recurly/resources/account.rb
  lib/recurly/resources/account_mini.rb
  lib/recurly/resources/dunning_campaign.rb
  lib/recurly/resources/dunning_campaigns_bulk_update_response.rb
  lib/recurly/resources/dunning_cycle.rb
  lib/recurly/resources/dunning_interval.rb
  lib/recurly/resources/invoice.rb
  lib/recurly/resources/plan.rb
  openapi/api.yaml
Labels: V4

#725 Generated Latest Changes for v2021-02-25 (Support to new subscription fields and response)
  lib/recurly/requests/subscription_change_shipping_create.rb
  lib/recurly/requests/subscription_update.rb
  lib/recurly/resources/subscription.rb
  openapi/api.yaml
Labels: V4

#726 Generated Latest Changes for v2019-10-10 (Added new response to subscription change)
  openapi/api.yaml
Labels: V3

#667 Add tests for subscription add-ons
  spec/fixtures/subscriptions/add_ons/show-200-updated.xml
  spec/fixtures/subscriptions/add_ons/show-200.xml
  spec/recurly/add_on_spec.rb
  spec/recurly/subscription_spec.rb
Labels: V2
