Repository recurly/recurly-client-ruby, pull requests merged in 2021-04, with the labels that each got.

#687 Generated Latest Changes for v2021-02-25
  openapi/api.yaml
Labels: V4

#688 Updating release scripts
  .changelog_config.yaml
  .github_changelog_generator
  scripts/bump
  scripts/changelog
  scripts/prepare-release
  scripts/release
Labels: V4, internal

#689 Updating release scripts
  .changelog_config.yaml
  .github_changelog_generator
  scripts/bump
  scripts/changelog
  scripts/prepare-release
  scripts/release
Labels: V3, internal

#690 Adding release scripts
  .changelog_config.yaml
  scripts/bump
  scripts/prepare-release
  scripts/release
Labels: V2, internal

#691 Generated Latest Changes for v2021-02-25 (Backup Payment Method)
  lib/recurly/requests/billing_info_create.rb
  lib/recurly/requests/subscription_purchase.rb
  lib/recurly/resources/billing_info.rb
  lib/recurly/resources/transaction.rb
  openapi/api.yaml
Labels: V4

#692 Triggers docs build on release being moved from pre-release to release
  .github/workflows/docs.yml
Labels: V4, internal

#693 Triggers docs build on release being moved from pre-release to release
  .github/workflows/docs.yml
Labels: V3, internal

#695 Generated Latest Changes for v2021-02-25
  lib/recurly/client/operations.rb
  lib/recurly/requests/subscription_add_on_tier.rb
  lib/recurly/resources/subscription_add_on_tier.rb
  openapi/api.yaml
Labels: V4

#694 Wallet and backup payment implementation
  lib/recurly/account.rb
  lib/recurly/billing_info.rb
  lib/recurly/invoice.rb
  lib/recurly/purchase.rb
  lib/recurly/subscription.rb
  spec/fixtures/billing_infos/create-201.xml
  spec/fixtures/billing_infos/index-200.xml
  spec/fixtures/billing_infos/show-200-updated.xml
  spec/fixtures/billing_infos/show-200.xml
  spec/recurly/billing_infos_spec.rb
Labels: V2, new feature

#697 Add prerenewal_notification webhook
  lib/recurly/webhook.rb
  lib/recurly/webhook/prerenewal_notification.rb
  spec/fixtures/webhooks/prerenewal-notification.xml
  spec/recurly/webhook/prerenewal_notification_spec.rb
  spec/recurly/webhook_spec.rb
Labels: V2

#699 Making #post allow a nil body
  lib/recurly/client.rb
  spec/recurly/client_spec.rb
Labels: V4, enhancement

#698 Making #post allow a nil body
  lib/recurly/client.rb
  spec/recurly/client_spec.rb
Labels: V3, enhancement
