Repository recurly/recurly-client-ruby, pull requests merged in 2021-03, with the labels that each got.

#671 Sync updates not ported from 3.x client
  .travis.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  lib/recurly/client.rb
  lib/recurly/pager.rb
  spec/recurly/client_spec.rb
Labels: V4

#673 Removing --binstubs from local development build script
  .github_changelog_generator
  scripts/build
  scripts/format
Labels: internal

#674 2019 rollup
  .github_changelog_generator
  scripts/build
  scripts/format
Labels: V4, internal

#678 Generated Latest Changes for v2021-02-25
  lib/recurly/client/operations.rb
  openapi/api.yaml
Labels: V4

#679 Additional fix for ruby 3.x
  lib/recurly/pager.rb
Labels: V3

#680 More ruby 3.0
  lib/recurly/pager.rb
Labels: V4

#682 Release 4.0.1
  .bumpversion.cfg
  lib/recurly/version.rb
Labels: V4

#683 Generated Latest Changes for v2021-02-25 (Usage Percentage on Tiers)
  lib/recurly/requests/add_on_create.rb
  lib/recurly/requests/add_on_update.rb
  lib/recurly/requests/tier.rb
  lib/recurly/resources/tier.rb
  openapi/api.yaml
Labels: V4

#672 Fixes TypeError caused by attempts to Base64 encode nil @api_key values
  lib/recurly/client.rb
  spec/recurly/client_spec.rb
Labels: V4

#685 Restoring NetworkError and it's derivatives
  lib/recurly/client.rb
  lib/recurly/errors.rb
  lib/recurly/errors/network_errors.rb
  spec/recurly/client_spec.rb
Labels: V4
