Repository recurly/recurly-client-ruby, pull requests merged in 2021-11, with the labels that each got.

#735 Allow API base url configuration
  lib/recurly/client.rb
  lib/recurly/connection_pool.rb
  spec/recurly/client_spec.rb
Labels: V4, internal

#738 Generated Latest Changes for v2019-10-10 (Account Hierarchy Invoice Rollup)
  lib/recurly/resources/line_item.rb
  openapi/api.yaml
Labels: V3

#739 Generated Latest Changes for v2021-02-25
  lib/recurly/requests/billing_info_create.rb
  lib/recurly/resources/line_item.rb
  openapi/api.yaml
Labels: V4
