Repository recurly/recurly-client-ruby, pull requests merged in 2021-06, with the labels that each got.

#702 Generated Latest Changes for v2021-02-25
  lib/recurly/client/operations.rb
  lib/recurly/requests/billing_info_create.rb
  lib/recurly/requests/billing_info_verify.rb
  lib/recurly/resources/billing_info.rb
  lib/recurly/resources/tax_detail.rb
  lib/recurly/resources/tax_info.rb
  openapi/api.yaml
Labels: V4

#705 Generated Latest Changes for v2021-02-25
  lib/recurly/resources/invoice.rb
  lib/recurly/resources/subscription_change.rb
  lib/recurly/resources/subscription_change_billing_info.rb
  openapi/api.yaml
Labels: V4

#704 Add tax_type and tax_region to TaxDetails
  lib/recurly/tax_detail.rb
  spec/fixtures/invoices/show-200-taxed.xml
  spec/recurly/invoice_spec.rb
Labels: V2

#706 Adds cc_bin_country to Recurly::BillingInfo resource
  lib/recurly/billing_info.rb
Labels: V2, enhancement

#696 Generated Latest Changes for v2019-10-10
  lib/recurly/client/operations.rb
  lib/recurly/requests/add_on_create.rb
  lib/recurly/requests/add_on_update.rb
  lib/recurly/requests/billing_info_create.rb
  lib/recurly/requests/subscription_purchase.rb
  lib/recurly/resources/billing_info.rb
  lib/recurly/resources/transaction.rb
  openapi/api.yaml
Labels: V3

#709 Generated Latest Changes for v2019-10-10
  lib/recurly/client/operations.rb
  lib/recurly/requests/address.rb
  lib/recurly/requests/billing_info_create.rb
  lib/recurly/requests/billing_info_verify.rb
  lib/recurly/requests/invoice_address.rb
  lib/recurly/requests/shipping_address_create.rb
  lib/recurly/requests/shipping_address_update.rb
  lib/recurly/requests/subscription_create.rb
  lib/recurly/requests/subscription_purchase.rb
  lib/recurly/resources/address.rb
  lib/recurly/resources/billing_info.rb
  lib/recurly/resources/billing_info_updated_by.rb
  lib/recurly/resources/invoice.rb
  lib/recurly/resources/invoice_address.rb
  lib/recurly/resources/payment_method.rb
  lib/recurly/resources/shipping_address.rb
  lib/recurly/resources/subscription_change.rb
  lib/recurly/resources/subscription_change_billing_info.rb
  lib/recurly/resources/subscription_change_preview.rb
  lib/recurly/resources/tax_detail.rb
  lib/recurly/resources/tax_info.rb
  lib/recurly/resources/transaction.rb
  openapi/api.yaml
Labels: V3
