Repository recurly/recurly-client-ruby, pull requests merged in 2022-04, with the labels that each got.

#765 Generated Latest Changes for v2019-10-10
  lib/recurly/resources/subscription.rb
  openapi/api.yaml
Labels: V3

#766 Generated Latest Changes for v2021-02-25
  lib/recurly/requests/add_on_create.rb
  lib/recurly/resources/add_on.rb
  lib/recurly/resources/subscription.rb
  lib/recurly/resources/subscription_add_on.rb
  openapi/api.yaml
Labels: V4

#763 Adding github actions for CI
  .github/workflows/ci.yml
  .travis.yml
Labels: V4, internal

#768 Adding github actions for CI
  .github/workflows/ci.yml
  .travis.yml
Labels: V3, internal

#769 Adding github actions for CI
  .github/workflows/ci.yml
  .travis.yml
  scripts/build
  scripts/test
Labels: V2, internal
