Repository recurly/recurly-client-ruby, pull requests merged in 2022-08, with the labels that each got.

#782 Generated Latest Changes for v2019-10-10
  lib/recurly/requests/plan_create.rb
  lib/recurly/requests/plan_pricing.rb
  lib/recurly/requests/plan_ramp_interval.rb
  lib/recurly/requests/plan_ramp_pricing.rb
  lib/recurly/requests/plan_update.rb
  lib/recurly/requests/subscription_change_create.rb
  lib/recurly/requests/subscription_create.rb
  lib/recurly/requests/subscription_purchase.rb
  lib/recurly/requests/subscription_ramp_interval.rb
  lib/recurly/resources/plan.rb
  lib/recurly/resources/plan_pricing.rb
  lib/recurly/resources/plan_ramp_interval.rb
  lib/recurly/resources/plan_ramp_pricing.rb
  lib/recurly/resources/subscription.rb
  lib/recurly/resources/subscription_change.rb
  lib/recurly/resources/subscription_change_preview.rb
  lib/recurly/resources/subscription_ramp_interval_response.rb
  openapi/api.yaml
Labels: V3

#783 Generated Latest Changes for v2021-02-25
  lib/recurly/requests/plan_create.rb
  lib/recurly/requests/plan_pricing.rb
  lib/recurly/requests/plan_ramp_interval.rb
  lib/recurly/requests/plan_ramp_pricing.rb
  lib/recurly/requests/plan_update.rb
  lib/recurly/requests/subscription_change_create.rb
  lib/recurly/requests/subscription_create.rb
  lib/recurly/requests/subscription_purchase.rb
  lib/recurly/requests/subscription_ramp_interval.rb
  lib/recurly/resources/payment_method.rb
  lib/recurly/resources/plan.rb
  lib/recurly/resources/plan_pricing.rb
  lib/recurly/resources/plan_ramp_interval.rb
  lib/recurly/resources/plan_ramp_pricing.rb
  lib/recurly/resources/subscription.rb
  lib/recurly/resources/subscription_change.rb
  lib/recurly/resources/subscription_ramp_interval_response.rb
  openapi/api.yaml
Labels: V4

#781 Added support for ramp-pricing plans
  lib/recurly.rb
  lib/recurly/plan.rb
  lib/recurly/plan_ramp_interval.rb
  spec/recurly/plan_spec.rb
Labels: V2

#784 Added support for ramp-pricing subscriptions
  lib/recurly.rb
  lib/recurly/resource.rb
  lib/recurly/subscription.rb
  lib/recurly/subscription_ramp_interval.rb
  spec/fixtures/subscriptions/serialize-with-ramps.xml
  spec/recurly/subscription_spec.rb
Labels: V2

#780 add username to billing info attributes
  lib/recurly/billing_info.rb
  spec/fixtures/billing_info/show-200-username.xml
  spec/recurly/billing_info_spec.rb
Labels: V2

#785 Added support for ramp-pricing purchases
  lib/recurly/adjustment.rb
  lib/recurly/invoice.rb
  spec/fixtures/purchases/authorize-with-ramp-pricing-201.xml
  spec/fixtures/purchases/invoice-with-ramp-pricing-201.xml
  spec/fixtures/purchases/pending-with-ramp-pricing-201.xml
  spec/fixtures/purchases/preview-with-ramp-pricing-201.xml
  spec/recurly/purchase_spec.rb
Labels: V2

#788 Fixes bug with put_dunning_campaign_bulk_update
  lib/recurly/client/operations.rb
  openapi/api.yaml
Labels: bug, V4
