Repository recurly/recurly-client-ruby, pull requests merged in 2022-11, with the labels that each got.

#806 Generated Latest Changes for v2019-10-10
  lib/recurly/client/operations.rb
  lib/recurly/requests/add_on_create.rb
  lib/recurly/requests/billing_info_create.rb
  lib/recurly/requests/plan_create.rb
  lib/recurly/requests/plan_update.rb
  lib/recurly/requests/subscription_add_on_create.rb
  lib/recurly/resources/plan.rb
  openapi/api.yaml
Labels: V3

#807 Generated Latest Changes for v2021-02-25
  lib/recurly/client/operations.rb
  lib/recurly/requests/add_on_create.rb
  lib/recurly/requests/billing_info_create.rb
  lib/recurly/requests/plan_create.rb
  lib/recurly/requests/plan_update.rb
  lib/recurly/requests/subscription_add_on_create.rb
  lib/recurly/resources/add_on.rb
  lib/recurly/resources/plan.rb
  lib/recurly/resources/subscription_add_on.rb
  lib/recurly/resources/usage.rb
  openapi/api.yaml
Labels: V4

#809 Generated Latest Changes for v2021-02-25 (External Subscriptions feature)
  lib/recurly/client/operations.rb
  lib/recurly/requests/add_on_create.rb
  lib/recurly/requests/add_on_update.rb
  lib/recurly/resources/add_on.rb
  lib/recurly/resources/external_product.rb
  lib/recurly/resources/external_product_reference_mini.rb
  lib/recurly/resources/external_resource_mini.rb
  lib/recurly/resources/external_subscription.rb
  lib/recurly/resources/subscription_add_on.rb
  openapi/api.yaml
Labels: V4

#810 Generated Latest Changes for v2019-10-10 (Apply Credit Balance feature)
  lib/recurly/client/operations.rb
  lib/recurly/resources/account_balance_amount.rb
  openapi/api.yaml
Labels: V3

#811 Generated Latest Changes for v2021-02-25 (Apply Credit Balance feature)
  lib/recurly/client/operations.rb
  lib/recurly/resources/account_balance_amount.rb
  openapi/api.yaml
Labels: V4

#812 V2 add support for Apply Credit Balance to existing invoice feature
  lib/recurly/account_balance.rb
  lib/recurly/invoice.rb
  spec/fixtures/account_balance/show-200.xml
  spec/recurly/account_spec.rb
  spec/recurly/invoice_spec.rb
Labels: V2

#813 Lock the version of jruby used in CI
  .github/workflows/ci.yml
Labels: V2, internal
