Repository recurly/recurly-client-ruby, pull requests merged in 2022-10, with the labels that each got.

#800 Generated Latest Changes for v2019-10-10(Decimal Usage and Quantities)
  lib/recurly/client/operations.rb
  lib/recurly/requests/line_item_refund.rb
  lib/recurly/requests/plan_ramp_interval.rb
  lib/recurly/requests/subscription_ramp_interval.rb
  lib/recurly/requests/usage_create.rb
  lib/recurly/resources/line_item.rb
  lib/recurly/resources/plan_ramp_interval.rb
  lib/recurly/resources/subscription_ramp_interval_response.rb
  lib/recurly/resources/usage.rb
  openapi/api.yaml
Labels: V3

#801 Generated Latest Changes for v2021-02-25(Decimal Usage and Quantities and DunningEvent new fields)
  lib/recurly/requests/billing_info_create.rb
  lib/recurly/requests/line_item_refund.rb
  lib/recurly/requests/usage_create.rb
  lib/recurly/resources/invoice.rb
  lib/recurly/resources/line_item.rb
  lib/recurly/resources/usage.rb
  openapi/api.yaml
Labels: V4

#804 Generated Latest Changes for v2021-02-25 (Entitlements feature)
  lib/recurly/client/operations.rb
  lib/recurly/resources/customer_permission.rb
  lib/recurly/resources/entitlement.rb
  lib/recurly/resources/entitlements.rb
  lib/recurly/resources/granted_by.rb
  openapi/api.yaml
Labels: V4

#798 Update client library to support entitlements
  lib/recurly.rb
  lib/recurly/account.rb
  lib/recurly/customer_permission.rb
  lib/recurly/entitlement.rb
  lib/recurly/external_subscription.rb
  spec/fixtures/accounts/entitlements/show-200.xml
  spec/fixtures/accounts/show-200.xml
  spec/recurly/account_spec.rb
Labels: new feature, V2
