Repository recurly/recurly-client-ruby, pull requests merged in 2023-04, with the labels that each got.

#833 Generated Latest Changes for v2021-02-25
  lib/recurly/requests/billing_info_create.rb
  lib/recurly/resources/external_charge.rb
  lib/recurly/resources/external_invoice.rb
  openapi/api.yaml
Labels: V4

#836 Generated Latest Changes for v2021-02-25 (External Accounts)
  lib/recurly/client/operations.rb
  lib/recurly/requests/account_create.rb
  lib/recurly/requests/external_account_create.rb
  lib/recurly/requests/external_account_update.rb
  lib/recurly/resources/account.rb
  lib/recurly/resources/external_account.rb
  openapi/api.yaml
Labels: V4

#837 Add used_tax_service to Invoice response
  lib/recurly/invoice.rb
  spec/fixtures/invoices/show-200-taxed.xml
  spec/recurly/invoice_spec.rb
Labels: V2

#838 Generated Latest Changes for v2019-10-10
  lib/recurly/requests/billing_info_create.rb
  lib/recurly/resources/custom_field_definition.rb
  lib/recurly/resources/invoice.rb
  openapi/api.yaml
Labels: V3
