Repository recurly/recurly-client-ruby, pull requests merged in 2023-01, with the labels that each got.

#816 Generated Latest Changes for v2021-02-25
  lib/recurly/client/operations.rb
  lib/recurly/requests/account_create.rb
  lib/recurly/requests/account_purchase.rb
  lib/recurly/requests/account_update.rb
  lib/recurly/requests/add_on_create.rb
  lib/recurly/requests/add_on_update.rb
  lib/recurly/requests/subscription_add_on_create.rb
  lib/recurly/requests/subscription_add_on_update.rb
  lib/recurly/resources/account.rb
  lib/recurly/resources/add_on.rb
  lib/recurly/resources/invoice.rb
  lib/recurly/resources/subscription_add_on.rb
  lib/recurly/resources/usage.rb
  openapi/api.yaml
Labels: V4

#815 Generated Latest Changes for v2019-10-10
  lib/recurly/client/operations.rb
  lib/recurly/requests/account_create.rb
  lib/recurly/requests/account_purchase.rb
  lib/recurly/requests/account_update.rb
  lib/recurly/resources/account.rb
  lib/recurly/resources/invoice.rb
  openapi/api.yaml
Labels: V3

#818 Added custom fields to adjustments
  lib/recurly/adjustment.rb
  spec/fixtures/adjustments/show-200.xml
  spec/recurly/adjustment_spec.rb
  spec/recurly/purchase_spec.rb
Labels: V2

#822 Generated Latest Changes for v2019-10-10 (Custom Fields on Line Items)
  lib/recurly/client/operations.rb
  lib/recurly/requests/line_item_create.rb
  lib/recurly/resources/line_item.rb
  openapi/api.yaml
Labels: V3

#823 Add Specs for Custom Fields on Adjustments in Invoice Responses
  spec/fixtures/invoices/show-200.xml
  spec/recurly/invoice_spec.rb
Labels: V2

#817 Added decline code to transaction error
  lib/recurly/transaction/errors.rb
  spec/fixtures/transaction_error.xml
  spec/recurly/transaction_spec.rb
Labels: V2
